apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  namespace: default
  name: cluster-issuer
spec:
  acme:
    email: {{LETS_ENCRYPT_EMAIL}}
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: cluster-issuer-secret
    solvers:
    - http01:
        ingress:
           class: nginx